### ISSUE TITLE
[tvOS15 and latest pyatv dev] Is atv wakeup currently not working?

### ISSUE THREAD

**Issue by jaddel** [postlund/pyatv#1365]
### What's on your mind?

I can't get homeassistant to wake my atv and make it show the homescreen, am I missing out on something?

I able to turn it of by - home_hold - select.

But turn_on or home_hold won't turn it back on.

Running:
HA core-2021.9.7
Added pyatv via hacs https://github.com/postlund/hass-atv-beta

**Comment by postlund** [comment]
Any of the regular navigation buttons should work, like `menu` for instance. Did you try that? It's currently not possible to call the `turn_on` function that's in the power interface of pyatv, that would have been ideal. Hopefully we can integrate better power management soon.

Can you try `menu` first? Otherwise it would be great if you could try `atvremote ... turn_on` (with AirPlay credentials) to see if that works. I

**Comment by jaddel** [comment]
i tried wakeup, home_hold, home and menu.

It's very strange, I just figured out that after every restart of HomeAssistant I can wake the atv once by:

```
alias: Apple TV wake
sequence:
  - service: remote.send_command
    target:
      entity_id: remote.living_room_apple_tv
    data:
      command: wakeup
mode: single
```

If I then turn it off by the apple remote and try to wake it again. 
I see this in the logs: `2021-10-01 18:15:40 ERROR (MainThread) [custom_components.apple_tv.remote] Unable to send commands, not connected to Living Room Apple TV`

I could reproduce this more than 5 times now. 


> Otherwise it would be great if you could try `atvremote ... turn_on` (with AirPlay credentials) to see if that works. 

How would I do that?

**Comment by jaddel** [comment]
I'm sorry if fund the issue. 

```
apple_tv_sleep:
  alias: "Make the Apple TV sleep"
  sequence:
    - service: remote.send_command
      target:
        entity_id: remote.lounge_appletv
      data:
        delay_secs: 1
        command:
          - home_hold
          - select
    - service: media_player.turn_off
      target:
        entity_id: media_player.lounge_appletv
```

I didn't realize that the last command of my sleep script is also disabling the media entity for further actions. 

Thank you for the quick response and the great work on pyatv!
