### ISSUE TITLE
Problem with using pyatv library. Please help!

### ISSUE THREAD

**Issue by DevIsLife777** [postlund/pyatv#1513]
### What to investigate?

Hello, my beautiful friends!

I am trying to integrate apple tv to my small smart home system. I try to use pyatv library under docker. I have Apple TV 4K, It have this config:

```raw
Scan Results
========================================
       Name: TL-OF
   Model/SW: Apple TV 4K (gen2), tvOS 15.0
    Address: 10.77.1.191
        MAC: F0:B3:EC:1F:DA:31
 Deep Sleep: False
Identifiers:
 - F0:B3:EC:1F:DA:31
 - F0B3EC1FDA31
Services:
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: Companion, Port: 49152, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
```

This command works correctly:
sudo docker run -it --rm --network=host ghcr.io/postlund/pyatv:master atvremote -s 10.77.1.191 --protocol companion pair
It returns credentials.

Also I try example from repository: manual_connect.py:

```python
import asyncio
from pyatv import conf, connect
from pyatv.const import Protocol
NAME = "My Apple TV"
ADDRESS = "10.77.1.191"
HSGID = "00000000-1111-2222-3333-444444444444"
LOOP = asyncio.get_event_loop()

async def print_what_is_playing(loop):
    config = conf.AppleTV(ADDRESS, NAME)
    config.add_service(
        conf.ManualService(**"123"**, Protocol.Companion, 49152, {}, credentials=HSGID)
    )
    print(f"Connecting to {config.address}")
    atv = await connect(config, loop)
    try:
        print(await atv.metadata.playing())
    finally:
        atv.close()
        
if __name__ == "__main__":
    LOOP.run_until_complete(print_what_is_playing(LOOP))
```

And it is not working:

```
Traceback (most recent call last):
  File "/app/apple_tv.py", line 24, in <module>
    LOOP.run_until_complete(print_what_is_playing(LOOP))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/app/apple_tv.py", line 17, in print_what_is_playing
    atv = await connect(config, loop)
  File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 81, in connect
    raise exceptions.DeviceIdMissingError("no device identifier")
pyatv.exceptions.DeviceIdMissingError: no device identifier
````

And I can't understand how I must use this lib, that this will work.

I am sorry for my bad english, my friend and thank you for your attention!

### Expected outcome

Connect to Apple TV and full control.

**Comment by postlund** [comment]
I suggest that you stay away from the "manual" example and use one that is based on scanning instead. This one is better:

https://github.com/postlund/pyatv/blob/master/examples/connect_with_credentials.py

Change identifiers to match your device, i.e.:

    "identifiers": {"F0:B3:EC:1F:DA:31", "F0B3EC1FDA31"},

As all the protocols need credentials (`Pairing: Mandatory` at the end) you need to pair them. In your case you have AirPlay, Companion and RAOP so you need to pair three times. It is possible to do this programmatically of course, but I suggest that you start by using `atvremote` and just add the credentials to your code as a start. So, first you do:

    atvremote --id F0B3EC1FDA31 --protocol airplay pair

You will get a long string which you should insert into your code. Then do the same thing again but change `airplay` to `companion` (you will get one long string more) and finally same thing again but with `raop` instead (yet another long string). All the strings shall be added to the code like this:

```yaml
DEVICES = [
    {
        "name": "TL-OF",
        "identifiers": {"F0:B3:EC:1F:DA:31", "F0B3EC1FDA31"},
        "credentials": {
            Protocol.AirPlay: "string from atvremote --id F0B3EC1FDA31 --protocol airplay pair here",
            Protocol.Companion: "same but from --protocol companion",
            Protocol.RAOP: "same but from --protocol raop",
        },
    },
    # Add more devices here
]
```
Hopefully it should work after that.
