### ISSUE TITLE
volume_set not working with tts.cloud_say

### ISSUE THREAD

**Issue by pug306d** [postlund/pyatv#1522]
### Describe the bug

I am trying to set the volume level when using the tts.cloud_say service in home assistant.

I can see the volume is changed correctly as per the first action but then when the HomePod plays the tts it automatically changes the volume to what appears to be 0.2, after it finishes and playing it sets the volume back to what was set in the first action even though I do not specify a second volume set action.

It appears to be related to the fact the tts message is played using RAOP which has different volume controls but I cannot see how to set those so the tts messages are played at a volume they can be heard?

### Error log

```log
<place log here>
```

### How to reproduce the bug?

Use these actions in a home assistant automation

action:
  - service: media_player.volume_set
    data:
      volume_level: 0.7
    target:
      entity_id: media_player.living_room_homepod
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: tts.cloud_say
    data:
      entity_id: media_player.living_room_homepod
      message: Test Message

### What is expected behavior?

The tts message is played at the volume set in the automation.

### Operating System

HassOS

### Python

3.9

### pyatv

latest?

### Device

HomePod Mini

### Additional context

None

**Comment by postlund** [comment]
Ah, this is a special little edge case I have missed. The only workaround right now is to set the volume after you started streaming, which I guess you can write an automaton for. But I will try to fix this before I release 0.9.8, which should happen some time this week.

**Comment by postlund** [comment]
I thought I understood what was happening, but I can't seem to reproduce this myself. What OS version are you running on your HomePod? I have a theory of what could happen with some devices, but I cannot explain why it would revert back to the volume you set prior to using `cloud_say` *after* the streaming finished. There's no code for that. If you can easily reproduce, please enable logging and send the logs to me so I can analyze them further.

**Comment by pug306d** [comment]
HomePod version is 15.1.1

When I first setup that automation I noticed the volume setting did not appear to apply when the tts was played on the HomePod so in the Home app on my iPhone I kept open the screen that lets me see what the HomePod is playing and its volume.  When the screen was open on my phone I run the automation and thats where I can see the volume is changed to the requested level, then tts is played with the lower volume and then the volume is changed back to the original value before the tts was played.

I have the HomePod and the HomePod mini and both are doing the same.

I did some more testing and it appears the tts is being played with a pre-configured volume for each device?  On my HomePod the tts is played at 0.7 always but on my HomePod Mini is is always played at 0.2.  I can set the volume either in the Home app or via media_player.volume_set and always the volume set is ignored when playing the tts.

I can change the volume whilst the tts is playing but when I play it again it plays at 0.7 for the HomePod or 0.2 on the Mini.

I found this on configuring logging but I'm not sure how to apply that on Home Assistant?

https://pyatv.dev/development/logging/

Thanks!

**Comment by postlund** [comment]
I have tried reproduce exactly like you did, but I can't seem to do that. Looking a logs is probably the easiest way forward. You have instructions for enabling them here:

https://github.com/postlund/hass-atv-beta#debug-logs

**Comment by pug306d** [comment]
I have the logs - there is a lot of information in them though which I don't want to share in a public forum, is there some specific entries I can share with you or some other way to share?

**Comment by postlund** [comment]
Definitely! Send them by email, you have it in my profile page.

**Comment by postlund** [comment]
Just wanted to check if you sent the logs or not (just so I didn't miss them)?

**Comment by 400HPMustang** [comment]
I have a similar problem so I thought instead of another bug I would just piggy back here I have the following automation:

```
alias: Test Announcements
description: Test Announcements on the office HomePod
trigger:
  - platform: time
    at: '08:00:00'
condition: []
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.office
  - service: tts.google_translate_say
    data:
      message: This is a test announcement
      entity_id: media_player.office
  - service: media_player.volume_set
    data:
      volume_level: 0.25
    target:
      entity_id: media_player.office
mode: single
```
I am seeing two different things happen:

1. When the media player is a single device (HomePod) the automation successfully sets the volume to 0.5 and makes the announcement. The trailing volume level call either is not occurring or is ignored but the volume stays at 0.5. 
2. When the media player is a group of devices (multiple HomePods) for some reason the volume sets to 0.25 before the announcement is made, then makes the announcement, and then the volume remains at 0.25
