### ISSUE TITLE
Multi-room synchronization for homepod/homepod-mini

### ISSUE THREAD

**Issue by muxiachuixue** [postlund/pyatv#1658]
### What feature would you like?

The last update regarding the full media controls of homepod is fantastic.
Will it be possible to add a feature to group multi-homepods in HA to play the media synchronously. That will be very cool!
The existing example is [sonos](https://www.home-assistant.io/integrations/sonos#service-sonosjoin).

### Describe the solution you'd like

Make it possible to group homepods to play media synchronously.

### Any other information to share?

I have tried to use the service `media_player.join` in HA, no luck.
```
service: media_player.join
data:
  group_members:
    - media_player.bedroom_homepodmini
    - media_player.living_room_homepodmini
target:
  entity_id:
    - media_player.living_room_homepodmini
```
