### ISSUE TITLE
TTS automations no longer working. 

### ISSUE THREAD

**Issue by 400HPMustang** [postlund/pyatv#1663]
### Describe the bug

Automations to trigger TTS on home pods are not currently working. They were working previously. The log shows the error below

### Error log

```log
This error originated from a custom integration.

Logger: custom_components.apple_tv.media_player
Source: custom_components/apple_tv/media_player.py:297
Integration: Apple TV
First occurred: 8:16:37 AM (2 occurrences)
Last logged: 8:17:36 AM

Media streaming is not possible with current configuration
```

### How to reproduce the bug?

Set up automation to play TTS message to homepod. Trigger automation.

### What is expected behavior?

The homepod would speak the message. 

### Operating System

Linux

### Python

3.9

### pyatv

Apple TV Beta 3.0.2

### Device

HomePod Mini 15.3

### Additional context

Here is my automation, which previously worked. Even triggering the actions manually does not work. 

```
alias: Test Announcements
description: Test Announcements on the office HomePod
trigger:
  - platform: time
    at: '08:00:00'
condition: []
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.office
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: tts.google_translate_say
    data:
      message: This is a test announcement
      entity_id: media_player.office
  - service: media_player.volume_set
    data:
      volume_level: 0.25
    target:
      entity_id: media_player.office
mode: single
```

Also HA info:

## System Health

version | core-2022.2.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.98
arch | x86_64
timezone | America/Chicago

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.22.0
Stage | running
Available Repositories | 1051
Downloaded Repositories | 32

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | beta
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 58.4 GB
disk_used | 8.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Check Home Assistant configuration (3.9.0), SSH & Web Terminal (10.0.2), Mosquitto broker (6.0.1), Ring-MQTT with Video Streaming (4.9.1), Home Assistant Google Drive Backup (0.105.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 39
views | 11
mode | storage

</details>
