### ISSUE TITLE
Playing camera via home assistant not working

### ISSUE THREAD

**Issue by mikeodr** [postlund/pyatv#1676]
### What do you need help with?

Was directed this way via the home assistant discord. Hopefully can confirm what I suspect is a codec problem.

Essentially I'm sending an RTSP camera in home assistant to my apple TV.:
```
service: media_player.play_media
data:
  media_content_id: camera.baby_high
  media_content_type: video
target:
  entity_id: media_player.apple_tv_living_room
```

Info:
* Apple TV 4K (gen2), Firmware: 15.3
* RTSP stream, H264 - MPEG-4 AVC (part10) (h264)
* pyatv  0.10.0 / Home assistant 2022.3

Logs: [pyatv logs](https://gist.github.com/mikeodr/d297c4555c331b2bbfd2806f2e25a9a3)

Its not clear to me from the logs what/why it fails outside of a HTTP 500 error.

Hoping for some further direction on debugging this further. Thanks.
