### ISSUE TITLE
tvOS 16 not working?

### ISSUE THREAD

**Issue by mschwartz** [postlund/pyatv#1841]
### Describe the bug

Perfectly working code, been working for months.

Upgraded the ATVs to tvOS16 and now pyatv throws an exception.  See log below.

### Error log

```log
ATV Connected to  THEATER 
    subscribe to  appletv/appletv-theater/set/command
Traceback (most recent call last):
  File "/home/app/./pyatv-microservice.py", line 337, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/app/./pyatv-microservice.py", line 171, in main
    atv = await pyatv.connect(device['appletv'], loop)
  File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 135, in connect
    await atv.connect()
  File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 546, in connect
    raise exceptions.NoServiceError("no service to connect to")
pyatv.exceptions.NoServiceError: no service to connect to```


### How to reproduce the bug?

Upgrade to 16 and try to connect.

### What is expected behavior?

Should work :)

### Operating System

macOS

### Python

3.10

### pyatv

whatever pip install pyatv installs

### Device

ATV tvOS 16

### Additional context

Not sure what to put here.

I'll try using master and see if that fixes anything.

**Comment by mschwartz** [comment]
Output from atvremote scan

```
      Name: THEATER
   Model/SW: Apple TV 4K (gen2), tvOS 16.0
    Address: 192.168.100.17
        MAC: 58:D3:49:EE:6F:D2
 Deep Sleep: False
Identifiers:
 - 58:D3:49:EE:6F:D2
 - 58D349EE6FD2
Services:
 - Protocol: Companion, Port: 49153, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - ```

**Comment by mschwartz** [comment]
I have 4 ATVs.  All updated to 16.

All fail the same manner.

All were working this morning.

Not sure if it's something I'm doing wrong (entirely possible), some API parameters I need to use that worked before, or if pyatv is broken with 16.  Could be something else..

NoServiceError is thrown.

**Comment by mschwartz** [comment]
Magic.  It started working today.

Could be some state the ATVs were in after the update.  Not sure.

**Comment by mschwartz** [comment]
What's interesting is the difference in the Apple TV data.  AirPlay shows credentials.

I really did nothing but leave it not running overnight and when I started it this AM, it just works.


```
Name: THEATER
   Model/SW: Apple TV 4K (gen2), tvOS 16.0
    Address: 192.168.100.17
        MAC: 58:D3:49:EE:6F:D2
 Deep Sleep: False
Identifiers:
 - 58:D3:49:EE:6F:D2
 - 58D349EE6FD2
Services:
 - Protocol: Companion, Port: 49153, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: AirPlay, Port: 7000, Credentials: 060ebb76xxx:, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
```
