### ISSUE TITLE
"power_off" in Home Assistant?

### ISSUE THREAD

**Issue by brad-newman** [postlund/pyatv#2184]
### What do you need help with?

I'm sending the "suspend" command to my ATV, which works in powering it off, but sometimes I can't wake my ATV after, even with the physical remote. The only solution is to unplug and plug back in. 

I don't see "power_off" in the HA ATV integration documentation, but see you've deprecated "suspend" here and replaced it with power_off (perhaps in part because of the issues I'm experiencing?)

Is there a different solution for HA, am I missing something? Thank you!

**Comment by brad-newman** [comment]
Properly implemented the home_hold script as documented:
```
apple_tv_sleep:
  alias: "Make the Apple TV sleep"
  sequence:
    - service: remote.send_command
      target:
        entity_id: remote.lounge_appletv
      data:
        delay_secs: 1
        command:
          - home_hold
          - select
    - service: media_player.turn_off
      target:
        entity_id: media_player.lounge_appletv
```
