### ISSUE TITLE
Home_hold not working anymore

### ISSUE THREAD

**Issue by mirceadb7** [postlund/pyatv#2286]
### Describe the bug

The Apple TV integration home_hold command is not correct, it’s command behavior like home command, it isn’t any difference.
on the last update when sending home_hold command the upper right menu will pop-up, now, on 2023.11.1 will send the home_hold command but the Apple TV only receives a home command.
In my automation I need home_hold to pop-up the upper menu and switch to Home app into a camera live feed

### Error log

```log
<place log here>
```

### How to reproduce the bug?

service: remote.send_command
data:
  num_repeats: 1
  delay_secs: 0.4
  hold_secs: 0
  command: home_hold
target:
  entity_id: remote.kitchen

### What is expected behavior?

Popup the upper menu on apple tv

### Operating System

macOS 

### Python

3.6

### pyatv

0.8.2

### Device

Apple TV 4K 17.1 OS

### Additional context

The issue has appeared on the latest Home Assistant version. core-2023.11.1

**Comment by apostoladriann** [comment]
Can confirm the same issue here as well. Same setup as mirceadb7. 

Currently running this work around script to turn off the apple tv 

```
alias: Apple TV - off
sequence:
  - service: media_player.select_source
    data:
      source: Settings
    target:
      entity_id: media_player.apple_tv_4k
  - service: remote.send_command
    data:
      command: down
      num_repeats: 14 <<- this is to make sure the selection goes to the end of the settings menu where the “sleep now” function is
      delay_secs: 0.2
    target:
      entity_id: remote.apple_tv_4k
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: remote.send_command
    data:
      command: select
    target:
      entity_id: remote.apple_tv_4k
mode: single
```

**Comment by mirceadb7** [comment]
> Can confirm the same issue here as well. Same setup as mirceadb7.
> 
> Currently running this work around script to turn off the apple tv
> 
> ```
> alias: Apple TV - off
> sequence:
>   - service: media_player.select_source
>     data:
>       source: Settings
>     target:
>       entity_id: media_player.apple_tv_4k
>   - service: remote.send_command
>     data:
>       command: down
>       num_repeats: 14 <<- this is to make sure the selection goes to the end of the settings menu where the “sleep now” function is
>       delay_secs: 0.2
>     target:
>       entity_id: remote.apple_tv_4k
>   - delay:
>       hours: 0
>       minutes: 0
>       seconds: 1
>       milliseconds: 0
>   - service: remote.send_command
>     data:
>       command: select
>     target:
>       entity_id: remote.apple_tv_4k
> mode: single
> ```

To turn off Apple TV, use `suspend` comand.

**Comment by apostoladriann** [comment]
Thanks, will test, seems like a more straight forward approach :) i appreciate the info.

However, remote home_hold is for a fact broken since core-2023.11.1. It acts like a regular remote home command since then.

**Comment by mirceadb7** [comment]
@postlund Do you have any update on the fix ? 🙏

**Comment by postlund** [comment]
@mirceadb7 Can you check if `atvremote ... home=2` works as expected? I will deprecate `home_hold` and it should not be used anymore.

**Comment by mirceadb7** [comment]
service: remote.send_command
target:
  entity_id: remote.kitchen
data:
  num_repeats: 1
  delay_secs: 0.4
  hold_secs: 0
  command: home=2

Failed to call service remote.send_command. Unknown error

**Comment by postlund** [comment]
It is not implemented in Home Assistant yet, there's a PR for it I think.

**Comment by mirceadb7** [comment]
> It is not implemented in Home Assistant yet, there's a PR for it I think.

PR? What is PR?

**Comment by postlund** [comment]
> > It is not implemented in Home Assistant yet, there's a PR for it I think.
> 
> PR? What is PR?

Pull Request. It's how you suggest code changes on github. I believe it will be merged for the next release, but I'm not 100% certain though. So easiest way to test is with atvremote.

**Comment by mirceadb7** [comment]
I can test it but I don’t know how

**Comment by stp6778** [comment]
You need to update remote.py
```
cd /usr/src/homeassistant/homeassistant/components/apple_tv
mv remote.py remote.py.ref
wget https://raw.githubusercontent.com/home-assistant/core/0f1d4f310340c0e20c00bf33dbcd78c491506da5/homeassistant/components/apple_tv/remote.py

```

And then you can test
```
service: remote.send_command
target:
  device_id: ...
data:
  num_repeats: 1
  delay_secs: 0.4
  hold_secs: 2
  command: home

```
