### ISSUE TITLE
Running atvremote in two different versions

### ISSUE THREAD

**Issue by seackone** [postlund/pyatv#347]
Hi,
im using pyatv on my raspberry pi 3 (raspbian buster lite) with python 3.7 and pyatv latest version 0.4.0a10. If im logged in to the raspberry (with user pi) via ssh, the scan and pairing process went very well.

```
pi@raspberrypi:~ $ atvremote scan
Scan Results
========================================
 Name: Living Room
 Address: 192.168.2.xxx
Identifiers:
 - A7334xxx-0xxx-4xxx-8xxx-242B12590xxx
 - Cx:6x:Cx:2x:Dx:7x
Services:
 - Protocol: MRP, Port: 49152, Credentials: None
 - Protocol: AirPlay, Port: 7000, Credentials: None
```

```
pi@raspberrypi:~ $ atvremote --id Cx:6x:Cx:2x:Dx:7x --protocol mrp pair
Enter PIN on screen: 8177

Pairing seems to have succeeded, yey!
You may now use these credentials: b8879e871cbf80909ebcec4b492ef684a10f854870e57bf4d2a27a4050ebxxxx:94a15265d06a63346127e9333a645b08078ee210daf24f07ea99a9cdafc7xxxx:38396431313365342d343964382d343965632d383136322d38623931653734343561xxxx:64346361326134622d626566662d343234342d613962632d38623131623638393262xxxx
```
Im able to send commands and everything works fine. For example:

```pi@raspberrypi:~ $ atvremote --id Cx:6x:Cx:2x:Dx:7x play```

Im using homebridge on my raspberry as well and also want to send the same shell commands with user "homebridge". Here is the log-file of homebridge:

```
Dez 29 10:09:32 raspberrypi homebridge[31412]: [2019-12-29 10:09:32] [Apple TV test]  failed: usage: atvremote [-h] [--name NAME] [--address ADDRESS] [-t TIMEOUT]
Dez 29 10:09:32 raspberrypi homebridge[31412]: [--version] [--remote-name REMOTE_NAME] [-p PIN]
Dez 29 10:09:32 raspberrypi homebridge[31412]: [--pairing-guid PAIRING_GUID] [-a | --login_id LOGIN_ID]
Dez 29 10:09:32 raspberrypi homebridge[31412]: [--airplay_credentials AIRPLAY_CREDENTIALS] [-v] [--debug]
Dez 29 10:09:32 raspberrypi homebridge[31412]: command [command ...]
Dez 29 10:09:32 raspberrypi homebridge[31412]: atvremote: error: unrecognized arguments: --id
```

The argument "--id" is not available. Even the commands of atvremote with user "pi" are completely different to the commands of user "homebridge". It looks like "homebridge" is using an older version of atvremote then "pi" but i dont know why. With user "pi", I can follow the instructions as described on this website: [https://postlund.github.io/pyatv//getting-started/](url), with user "homebridge", everything looks like described on this page: [https://pyatv.readthedocs.io/en/master/atvremote.html](url)

Is there anybody who can help me out? With user "pi", im able to scan and find my apple tv but if im running the scan command with user "homebridge", I can not find any devices.
