### ISSUE TITLE
HA integration: only play/pause works

### ISSUE THREAD

**Issue by JorgeAnzola** [postlund/pyatv#401]
Hi, man! First of all, thanks for working on this! I'm a complete rookie in HA, and my Apple TV has been the first guinea pig. I managed to install HACS and the repo and to get the credentials with `atvremote` (Not the dmap creds, tho).

In the card, I see what's playing and the art cover, but only the play/pause button works, nothing else. This is my config, am I missing something?

```
apple_tv:
  - host: 192.168.178.30
    identifier: CC:**:**:**:**:**
    name: Living Room
    protocol: MRP
    credentials:
      mrp: a9d7****
      airplay: 7277****
```

If you could drop me a hint would be highly appreciated 🙌🏻
