### ISSUE TITLE
Remote async_send_command ERROR

### ISSUE THREAD

**Issue by tommyjlong** [postlund/pyatv#439]
**Describe the bug**
Getting the following Log entries (seems to correlate each time a remote.send service call is invoked) :
`2020-02-10 16:11:56 ERROR (MainThread) [homeassistant.helpers.service] Service async_send_command for remote.family_room2 incorrectly returns a coroutine object. Await result instead in service handler. Report bug to integration author.`
**To Reproduce**
I'm using a script.  The following is a simple one that causes one log entry to be produced:
```
  test_appletv2:
    alias: Test Apple TV
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.family_room2
          command:
            - home_hold

```
Otherwise, the script however does work correctly.

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: [e.g. Debian]  Ubuntu 18.04
 - Python: [e.g. 3.6.2] Python 3.7.5 in venv 
 - pyatv: [e.g. 0.3.10]  pyatv-0.4.0a13
 - HA 0.105.2

**Additional context**
