### ISSUE TITLE
HASS send multiple commands in single action

### ISSUE THREAD

**Issue by WizBangCrash** [postlund/pyatv#842]
Hi,
Thanks for the great work in developing this much needed integration for HASS :-)

I have a question around using the `remote.send_command` service in HASS
I want to do this:
```yaml
action:
 - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command: 
        - top_menu
        - delay=1000
        - home
        - delay=1000
        - right
        - delay=1000
        - select
```

But it doesn't seem to work. Sometimes the first command gets executed, but most times nothing happens and I do not see any errors in the log either.

When I changed it to this it works:
```yaml
  action:
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command: top_menu
  - delay: 2
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command: home
  - delay: 1
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command: right
  - delay: 1
  - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command: select
```

I'm new to HASS so I'm feel like I'm just doing something wrong, but can't figure it out.
Any pointers would be really useful. Thanks.

**Comment by WizBangCrash** [comment]
Hi @postlund 
I got to the bottom of my question last night and realised the apple_tv integration does not currently support a delay command.
I made the following mod to the remote.py `async_send_command` and wondered if you would be happy to include this in the next iteration of `hass-atv`

```python
    async def async_send_command(self, command, **kwargs):
        """Send a command to one device."""
        if not self.is_on:
            _LOGGER.error("Unable to send commands, not connected to %s", self._name)
            return

        for single_command in command:
            _LOGGER.info("Sending command %s", single_command)
            if single_command.startswith("delay="):
                delay = single_command[6:]
                try:
                    float(delay)
                except:
                    _LOGGER.error("Command delay must be a numeric %s", single_command)
                else:
                    await asyncio.sleep(float(delay))
            elif not hasattr(self.atv.remote_control, single_command):
                _LOGGER.error("No attributes for command %s", single_command)
                continue
            else:
                await getattr(self.atv.remote_control, single_command)()
```

The mod treats the delay as number of seconds, so my original action ends up as:

```yaml
action:
 - service: remote.send_command
    data:
      entity_id: remote.lounge_atv
      command: 
        - top_menu
        - delay=1.5
        - home
        - delay=1
        - right
        - delay=1
        - select
```

If you would prefer I can fork the repo and send you a pull request with my changes.
